# Generated by Django 6.0.7 on 2026-08-09 09:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifestyleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_frequency', models.CharField(choices=[('never', 'Never'), ('sometimes', 'Sometimes'), ('often', 'Often'), ('usually', 'Usually'), ('always', 'Always')], max_length=30)),
                ('noise_generating_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=30)),
                ('noise_tolerance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=30)),
                ('social_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('smoking', models.BooleanField(null=True)),
                ('has_pets', models.BooleanField(null=True)),
                ('cooking', models.CharField(choices=[('never', 'Never'), ('sometimes', 'Sometimes'), ('often', 'Often'), ('usually', 'Usually'), ('always', 'Always')], max_length=30)),
                ('eating_at_home', models.CharField(choices=[('never', 'Never'), ('sometimes', 'Sometimes'), ('often', 'Often'), ('usually', 'Usually'), ('always', 'Always')], max_length=30)),
                ('wake_up', models.TimeField()),
                ('sleep', models.TimeField()),
                ('guests', models.CharField(choices=[('never', 'Never'), ('sometimes', 'Sometimes'), ('often', 'Often'), ('usually', 'Usually'), ('always', 'Always')], max_length=12)),
                ('overnight_guests', models.CharField(choices=[('never', 'Never'), ('sometimes', 'Sometimes'), ('often', 'Often'), ('usually', 'Usually'), ('always', 'Always')], max_length=12)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanliness_weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('noise_weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('social_weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('pets_weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('cooking_weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('guests_weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('sleep_schedule_weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('accepts_smokers', models.BooleanField(null=True)),
                ('accepts_pets', models.BooleanField(null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField()),
                ('job', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, max_length=200)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
