# Generated by Django 6.0.7 on 2026-08-03 06:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_account_accept_pets_remove_account_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifestyleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_frequency', models.CharField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('often', 'often'), ('usually', 'usually'), ('always', 'always')], max_length=30)),
                ('noise_generating_level', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=30)),
                ('noise_tolerance', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=30)),
                ('social_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('smoking', models.BooleanField()),
                ('has_pets', models.BooleanField()),
                ('cooking', models.CharField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('often', 'often'), ('usually', 'usually'), ('always', 'always')], max_length=30)),
                ('eating_at_home', models.CharField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('often', 'often'), ('usually', 'usually'), ('always', 'always')], max_length=30)),
                ('wake_up', models.TimeField()),
                ('sleep', models.TimeField()),
                ('guests', models.CharField(verbose_name=(('never', 'never'), ('sometimes', 'sometimes'), ('often', 'often'), ('usually', 'usually'), ('always', 'always')))),
                ('overnight_guests', models.CharField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('often', 'often'), ('usually', 'usually'), ('always', 'always')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanliness_weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('noise_weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('social_weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('pets_weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('cooking_weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('guests_weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('sleep_schedule_weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('accepts_smokers', models.BooleanField()),
                ('accepts_pets', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrhdate', models.TimeField()),
                ('job', models.CharField(max_length=20)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='accounts.account', verbose_name='account')),
            ],
        ),
    ]
