# Generated by Django 6.0.7 on 2026-08-13 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifestyleprofile',
            old_name='social_level',
            new_name='cleanliness',
        ),
        migrations.RenameField(
            model_name='lifestyleprofile',
            old_name='guests',
            new_name='guests_frequency',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='accepts_smokers',
            new_name='accepts_smoking',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='cleanliness_weight',
            new_name='cleanliness_importance',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='cooking_weight',
            new_name='cooking_importance',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='guests_weight',
            new_name='guests_importance',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='noise_weight',
            new_name='max_guests_frequency',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='pets_weight',
            new_name='max_noise',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='sleep_schedule_weight',
            new_name='noise_importance',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='social_weight',
            new_name='preferred_social_activity',
        ),
        migrations.RemoveField(
            model_name='lifestyleprofile',
            name='cleaning_frequency',
        ),
        migrations.RemoveField(
            model_name='lifestyleprofile',
            name='eating_at_home',
        ),
        migrations.RemoveField(
            model_name='lifestyleprofile',
            name='noise_generating_level',
        ),
        migrations.RemoveField(
            model_name='lifestyleprofile',
            name='noise_tolerance',
        ),
        migrations.RemoveField(
            model_name='lifestyleprofile',
            name='overnight_guests',
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='noise_generating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='social_activity',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='sleep_schedule_importance',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='social_importance',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
