# Generated by Django 6.0.7 on 2026-08-02 20:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('job', models.CharField(max_length=20)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('wake_up', models.TimeField()),
                ('sleep', models.TimeField()),
                ('cleanliness', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('cleaning_frequency', models.CharField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('often', 'often'), ('usually', 'usually'), ('always', 'always')], max_length=30)),
                ('noise_tolerance', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=30)),
                ('smoking', models.BooleanField()),
                ('has_pets', models.BooleanField()),
                ('accept_pets', models.BooleanField()),
                ('cooking', models.CharField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('often', 'often'), ('usually', 'usually'), ('always', 'always')], max_length=30)),
                ('eating_at_home', models.CharField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('often', 'often'), ('usually', 'usually'), ('always', 'always')], max_length=30)),
                ('guests', models.CharField(verbose_name=(('never', 'never'), ('sometimes', 'sometimes'), ('often', 'often'), ('usually', 'usually'), ('always', 'always')))),
                ('overnight_guests', models.CharField(choices=[('never', 'never'), ('sometimes', 'sometimes'), ('often', 'often'), ('usually', 'usually'), ('always', 'always')], max_length=40)),
                ('social_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('prefer', models.CharField(choices=[('always together', 'always together'), ('sometimes hang out', 'sometimes hang out'), ('personal space', 'personal space')], max_length=30)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='locations.city', verbose_name='city')),
            ],
        ),
    ]
