# Generated by Django 6.0.7 on 2026-08-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='accept_pets',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cleaning_frequency',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cleanliness',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cooking',
        ),
        migrations.RemoveField(
            model_name='account',
            name='eating_at_home',
        ),
        migrations.RemoveField(
            model_name='account',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='account',
            name='has_pets',
        ),
        migrations.RemoveField(
            model_name='account',
            name='job',
        ),
        migrations.RemoveField(
            model_name='account',
            name='noise_tolerance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='overnight_guests',
        ),
        migrations.RemoveField(
            model_name='account',
            name='prefer',
        ),
        migrations.RemoveField(
            model_name='account',
            name='sleep',
        ),
        migrations.RemoveField(
            model_name='account',
            name='smoking',
        ),
        migrations.RemoveField(
            model_name='account',
            name='social_level',
        ),
        migrations.RemoveField(
            model_name='account',
            name='wake_up',
        ),
    ]
